### ISSUE TITLE
Quotes in multiple words search

### ISSUE THREAD

**Issue by George-Developer-1** [bantya/Keypirinha-EasySearch#7]
When searching for more than one word with space between, it gives URL in quotes and leads to error.
Examples:
Definition:   gm = Google_maps https://www.google.cz/maps/search/{q}?hl=cs&source=opensearch

Keypirihna enter : gm New York
It opens Chrome and put in ULR:   %22https//www.google.cz/maps/search/New%20York?hl=cs&source=opensearch"
..probably it sends to Chrome: "https//www.google.cz/maps/search/New York?hl=cs&source=opensearch"

Keypirihna enter : gm London
Result - OK:  https://www.google.cz/maps/search/London?hl=cs&source=opensearch

Google Chrome Version: 86.0.4240.75
May be option, how to handle spaces in argument should be added (see eg. line #92 here:  https://github.com/Keypirinha/Packages/blob/master/WebSearch/websearch.ini )

**Comment by Davix-Pixie** [comment]
at first multi word search used to work like a charm.. but now I think due to some changes in the settings of either of the browser, or easysearch.

either way the google searches use "+" rather than "%20
Therefore, an option to how to handle spaces in argument to be included is a must

(#. not a developer or used to github, pardon for any unfamiliar language)

**Comment by George-Developer-1** [comment]
Confirm, that about 2 month ago, there was no problem with Chrome even with multi word with spaces. May be some change on Google Chrome side.. Also confirm, that "+" instead of space works (but is it good way?)

**Comment by Davix-Pixie** [comment]
Using "+" instead of spaces is in no way "good"...Thus the plugin needs to be updated to support custom handling of space argument for different engines.

Until then I'm forced to use "+" instead.

(#. please do comment if u do know of any better way)

**Comment by George-Developer-1** [comment]
After update Keypirinha to v 2.26 problem disappeared (see https://keypirinha.com/changelog.html  or below).
Suggest to close this topic as solved.

_v2.26 - 2020-11-08
Fixed: trouble opening Google Chrome when configured as system default web browser (#474)_

**Comment by bantya** [comment]
Good to hear that. 
Take care .. 👍🏽
